### ISSUE TITLE
Can't Insert Own Model

### ISSUE THREAD

**Issue by Hollywood42** [lobe/android-bootstrap#10]
The app works great with the default model but when I insert my own and try to run it I get a black screen and the green bar says default. If I exit and come back in it crashes. The steps I followed are:
1. Renamed my model "model_unquant"
2. replaced the old one in "*\android-bootstrap\lobe_android\app\src\main\assets"
3. change the text in labels.txt to the labels my model uses.

**Comment by Hollywood42** [comment]
Here's the logcat (I set it to error mode): 
[Error Log.txt](https://github.com/lobe/android-bootstrap/files/5467499/Error.Log.txt)

**Comment by dcaravana** [comment]
Same here: exported the model as Tensorflow Lite from Lobe (tried speed/accuracy, optimised/not optimised), followed the same steps as @Hollywood42 and got the same exact error.

Reporting it here for convenience:

```
    java.lang.AssertionError: TensorBuffer does not support data type: STRING
        at org.tensorflow.lite.support.tensorbuffer.TensorBuffer.createFixedSize(TensorBuffer.java:82)
        at com.example.test.tflite.Classifier.<init>(Classifier.java:239)
        at com.example.test.tflite.ClassifierFloatMobileNet.<init>(ClassifierFloatMobileNet.java:47)
        at com.example.test.tflite.Classifier.create(Classifier.java:119)
        at com.example.test.DetectorActivity.recreateClassifier(DetectorActivity.kt:71)
        at com.example.test.DetectorActivity.onPreviewSizeChosen(DetectorActivity.kt:95)
        at com.example.test.CameraActivity.onPreviewFrame(CameraActivity.kt:278)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1227)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Funnily enough, I wasn't able to find much about that error over the Internet.

I found a really weird workaround (which I'm not even going to mention here because it's an absolute hack) but it's clear there is a problem in the exported model and/or in the version of Tensorflow Lite in use (mostly gut feeling here, I'm far from being a Tensorflow expert).

**Comment by EXCALOFRIO** [comment]
I have the same problem :(

**Comment by christli7** [comment]
now it looks like I have the same problem too
![image](https://user-images.githubusercontent.com/73643273/97785861-3ae77580-1bda-11eb-9a21-a9cf65d25eaa.png)

**Comment by dcaravana** [comment]
@christli7 not sure it's the same problem, in fact in my case the app completely crashes and closes, so you should be seeing Android's home screen.

Did you connect a real webcam to that Android emulator? Search for it if not, it's quite easy.

Also double-tapping on the app page swaps between available webcams.

**Comment by christli7** [comment]
ok now it crashes
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.test, PID: 9091
    java.lang.AssertionError: TensorBuffer does not support data type: STRING
        at org.tensorflow.lite.support.tensorbuffer.TensorBuffer.createFixedSize(TensorBuffer.java:82)
        at com.example.test.tflite.Classifier.<init>(Classifier.java:236)
        at com.example.test.tflite.ClassifierFloatMobileNet.<init>(ClassifierFloatMobileNet.java:47)
        at com.example.test.tflite.Classifier.create(Classifier.java:119)
        at com.example.test.DetectorActivity.recreateClassifier(DetectorActivity.kt:71)
        at com.example.test.DetectorActivity.onPreviewSizeChosen(DetectorActivity.kt:95)
        at com.example.test.CameraActivity.onPreviewFrame(CameraActivity.kt:278)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1227)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Hollywood42** [comment]
Mine has the black screen after I allow it to use my camera and then if I exit and come back in it crashes. So that looks like it is the same issue @christli7

**Comment by EXCALOFRIO** [comment]
We all have the same problem, and the problem is the .tflite file

**Comment by EXCALOFRIO** [comment]
> Todos tenemos el mismo problema, y ​​el problema es el archivo .tflite

The version of the original .tflite is 1.6.0 and the one generated by LOBE is 1.9.0

**Comment by MaorDayanOfficial** [comment]
app is crushing or just stuck with black screen like the picture above, please update all the files to the most updated version and fix it

**Comment by adammenges** [comment]
Thanks for reporting this! We're looking into this now! 😄

**Comment by EXCALOFRIO** [comment]
When is the error going to be fix?

**Comment by christli7** [comment]
👀

**Comment by EXCALOFRIO** [comment]
When will it be ready?

**Comment by luizabbadia** [comment]
Hi! I have a problem when  using the model in Android. Only the second class of the model is chosen, as shown in tha attached file,
![Screenshot_20210214-135741](https://user-images.githubusercontent.com/5408366/108118329-1d112400-7096-11eb-87a6-bba676f44670.jpg)

**Comment by luizabbadia** [comment]
I create another Lobe model with 10 classes but, still, it gives me only the last class.
![Uploading Screenshot_20210216-210452.jpg…]()

**Comment by luizabbadia** [comment]
I create another Lobe model with 10 classes but, still, it gives me only the last class.
![Screenshot_20210216-210452](https://user-images.githubusercontent.com/5408366/108123031-218d0b00-709d-11eb-8554-bd1aca8301cc.jpg)

**Comment by lemillermicrosoft** [comment]
Please pull the latest as this starter project was updated in #18 . If you are still seeing issues, please let us know. Sorry it took some time!

**Comment by lemillermicrosoft** [comment]
Also ensure you are using the latest 0.9 version of Lobe when exporting your model. Additionally, you should select 'Speed' template for the project settings before training+exporting for the best performance. If there are issues, please file new issues for better tracking.
