### ISSUE TITLE
App crashes with "x + width must be <= bitmap.width()" Error on Google Pixel 2

### ISSUE THREAD

**Issue by nahakiole** [lobe/android-bootstrap#14]
`````
2021-02-12 02:31:50.669 22168-22233/com.example.test E/AndroidRuntime: FATAL EXCEPTION: inference
Process: com.example.test, PID: 22168
java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
        at android.graphics.Bitmap.createBitmap(Bitmap.java:876)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
        at com.example.test.DetectorActivity$processImage$1.run(DetectorActivity.kt:200)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
`````

I've cloned the source, installed everything and was able to install the app on my phone. But when I run it I get this error in my logcat. First I though I need to replace the ml model with my own, but after replacing it the error stayed.

The problem seems to be here: https://github.com/lobe/android-bootstrap/blob/main/lobe_android/app/src/main/java/com/example/test/DetectorActivity.kt#L195

```
rawBitmap = Bitmap.createBitmap(rotatedBitmap, 0, 0, w.toInt(), rotatedBitmap.height)
```

I'm testing it on a Google Pixel 2 with Android 11, API 30 and also a LGE Nexus 5X Android 8.1.0, API 27 with the same result on both devices.

Rest of logcat

```
2021-02-12 02:31:49.598 22168-22168/? I/om.example.tes: Late-enabling -Xcheck:jni
2021-02-12 02:31:49.621 22168-22168/? I/om.example.tes: Unquickening 12 vdex files!
2021-02-12 02:31:49.758 22168-22168/com.example.test D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-02-12 02:31:49.759 22168-22168/com.example.test D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-02-12 02:31:49.860 22168-22168/com.example.test I/CameraManagerGlobal: Connecting to camera service
2021-02-12 02:31:49.912 22168-22168/com.example.test D/tensorflow: CameraActivity: onStart com.example.test.DetectorActivity@47e81ce
2021-02-12 02:31:49.916 22168-22168/com.example.test D/tensorflow: CameraActivity: onResume com.example.test.DetectorActivity@47e81ce
2021-02-12 02:31:49.951 22168-22230/com.example.test I/AdrenoGLES-0: QUALCOMM build                   : 02fe52e, Ie73904e3bd
    Build Date                       : 06/27/20
    OpenGL ES Shader Compiler Version: EV031.31.04.00
    Local Branch                     : gfx-adreno.lnx.2.0
    Remote Branch                    : quic/gfx-adreno.lnx.2.0
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2021-02-12 02:31:49.951 22168-22230/com.example.test I/AdrenoGLES-0: Build Config                     : S L 10.0.5 AArch64
2021-02-12 02:31:49.951 22168-22230/com.example.test I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2021-02-12 02:31:49.954 22168-22230/com.example.test I/AdrenoGLES-0: PFP: 0x005ff112, ME: 0x005ff066
2021-02-12 02:31:49.957 22168-22230/com.example.test W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2021-02-12 02:31:49.957 22168-22230/com.example.test W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2021-02-12 02:31:50.037 22168-22168/com.example.test I/tensorflow: CameraConnectionFragment: Desired size: 1280x960, min size: 960x960
2021-02-12 02:31:50.037 22168-22168/com.example.test I/tensorflow: CameraConnectionFragment: Valid preview sizes: []
2021-02-12 02:31:50.037 22168-22168/com.example.test I/tensorflow: CameraConnectionFragment: Rejected preview sizes: [1280x720]
2021-02-12 02:31:50.037 22168-22168/com.example.test E/tensorflow: CameraConnectionFragment: Couldn't find any suitable preview size
2021-02-12 02:31:50.057 22168-22217/com.example.test I/Gralloc4: mapper 4.x is not supported
2021-02-12 02:31:50.057 22168-22217/com.example.test W/Gralloc3: mapper 3.x is not supported
2021-02-12 02:31:50.064 22168-22217/com.example.test W/Gralloc4: allocator 3.x is not supported
2021-02-12 02:31:50.064 22168-22217/com.example.test W/Gralloc3: allocator 3.x is not supported
2021-02-12 02:31:50.274 22168-22168/com.example.test D/tensorflow: DetectorActivity: Creating classifier (model=FLOAT_MOBILENET, device=CPU, numThreads=4)
2021-02-12 02:31:50.285 22168-22168/com.example.test I/tflite: Initialized TensorFlow Lite runtime.
2021-02-12 02:31:50.294 22168-22168/com.example.test D/tensorflow: Classifier: Created a Tensorflow Lite Image Classifier.
2021-02-12 02:31:50.295 22168-22168/com.example.test I/tensorflow: DetectorActivity: Camera orientation relative to screen canvas: 90
2021-02-12 02:31:50.296 22168-22168/com.example.test I/tensorflow: DetectorActivity: Initializing at size 1280x720
2021-02-12 02:31:50.667 22168-22233/com.example.test D/INFO: 1919
2021-02-12 02:31:50.668 22168-22233/com.example.test D/INFO: 3189
2021-02-12 02:31:50.668 22168-22233/com.example.test D/INFO: 1794
2021-02-12 02:31:50.669 22168-22233/com.example.test E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: com.example.test, PID: 22168
    java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
        at android.graphics.Bitmap.createBitmap(Bitmap.java:876)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
        at com.example.test.DetectorActivity$processImage$1.run(DetectorActivity.kt:200)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-02-12 02:31:50.685 22168-22233/com.example.test I/Process: Sending signal. PID: 22168 SIG: 9
```

**Comment by JakeCohenMicrosoft** [comment]
Thank you for reporting this nahakiole. I will forward this to our team to help investigate.

**Comment by Hollywood42** [comment]
I'm getting a similar error on my google pixel 3, I attached my error log in case that helps solve the issue. 
[error.txt](https://github.com/lobe/android-bootstrap/files/6078348/error.txt)

**Comment by nahakiole** [comment]
I think that is a different problem:

Excerpt from the error.txt:
```
2021-02-23 22:53:30.264 3139-3139/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pvpn.privatevpn, PID: 3139
    java.lang.RuntimeException: Unable to create application com.pvpn.privatevpn.VPNApplication: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6720)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
```

I've searched through the logs and haven't found an bitmap related exception. This seems more like a VPN error? Or did you attach the wrong logfile?

**Comment by Hollywood42** [comment]
Yeah I think you're right, I saw the java illegal exception part and didn't look into much more. Sorry.

**Comment by lemillermicrosoft** [comment]
We've updated and made a few changes in this area. At best, it should not be crashing anymore. Can you respond and reactivate if you are still seeing the issue? Thanks!
